Code0Em/lingua-sonnet

assets/css/reset.css
Created assets directory and within this, CSS and JS directories. Created index.html, script.js and styles.css files. Copied previously provided reset.css file to CSS directory (added credit to this).
=> Organised Repo

index.html
has a nav bar, and three different section containing a input text section, a defination section and a poetry section
=> HTML has a nav bar, and three different seciton containing a input t

assets/js/script.js, index.html
JS: Constructed API url for PoetryDB. Created function which “fetches” a random poem from the API. Created event listener on generate poem button (so that when the user selects the button, the above "fetch" function is called).
HTML: Added some more ids, so can grab these references for the JS.
=> Started JS for Poetry API

assets/css/reset.css, assets/css/styles.css, index.html
=> added bootstrap CDN, cards, formatting, provisional google font for title

assets/js/script.js, index.html
JS: Created a function which checks if the random poem (from the API) contains the user’s word. If it does, the poem is displayed on the page. If it doesn’t, another random poem is generated up to a maximum of ten times. After which, error message is displayed.
HTML: Added id to generate poem button (for grab in function above).
STILL TO DO: Grab the user's word from the input field and incorporate it into above function.
=> JS for Poetry API (checks random poem for user’s word)

assets/js/script.js
JS: Added pseudocode for Dictionary API tasks. Created query url for Dictionary URL, send endpoint as the user’s word.
=> JS: Query url for Dictionary API

assets/css/styles.css, index.html
My HTML branch has a merge conflict so I created this new branch called WORDHISTORY
=> new branch create named WORDHISTORY where the new section for word history will be coded for

assets/js/script.js, index.html
JS: Created fetch function for Dictionary URL.
=> JS: Fetch function for Dictionary API

assets/js/script.js, index.html
JS: Added event listener for definition button, which calls the fetch function for the Dictionary API.
=> JS: Event listener for Definition button

assets/js/script.js, index.html
JS: Created a function which displays a definition of the user's word.
=> JS: Function to display definition

assets/js/script.js, index.html
JS: Added an if/else statement to fetch function on Dictionary API, so that an error message is displayed to the user if the API returns an error.
=> JS: If/else statement for error message from API

assets/css/styles.css, assets/js/script.js, index.html
HTML: Changed textarea element to an input element and set max character (so user can’t enter paragraphs/impossibly long words). Added code comments to explain changes to collabs. Formatted document.
CSS: Add styling to the input element (so it’s bigger).
JS: Fixed existing functions so the error messages are displayed when user doesn’t enter a word in the input element.
=> Fixes to input word field and functions when no word is entered by user

assets/js/script.js, index.html
HTML: Hard coded bootstrap spinners to the definition and poem cards.
JS: Added/removed classes in functions, so that spinners are displayed appropriately.
=> Added loading spinners

assets/js/script.js, index.html
HTML: Hard coded section for word history buttons to “live”.
JS: Created functions and event listeners which store the user’s word to local storage and create a word history button for the word; then retrieve the word when the user selects said button.
=> Added local storage and “word history buttons” functionality

assets/css/styles.css, assets/js/script.js, index.html
HTML: Hard coded bootstrap modal.
JS: Added code to existing functions so that modals are displayed as required.
CSS: Updated history buttons text (so it’s as appears on @codeswitchstudio screenshot).
=> Added Bootstrap Modal for all error messages

README.md, assets/js/script.js
JS: Removed speechmarks from definition and poem returned from APIs.
=> Removed speechmarks from definition and poem

README.md, assets/js/script.js
README: added a contents and some other sections.
JS: Added credit used for modals.
=> Added structure and some more content to README

assets/js/script.js, index.html
JS: Added code to existing functions so that poem author and title now displayed also.
=> Added poem title and author

assets/css/styles.css
=> Poetry Container - Fonts of text changed

README.md, assets/js/script.js
JS: Formatted document so code is indented as per best practice. Removed all console logs (which were for testing purposes). Added code to start button event listener so that any previous confirmation message is cleared and an error message is displayed if the user’s included a space in their word. Added a different error message in the poem and definition event listeners so it now tells users they haven’t saved a word.
README: Added links to our GitHubs. Added credit.
=> Tidied JS code, added more functionality to JS and added credit/links to README
